config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :roles
  resources :jobs
  resources :users do
    member do
      get 'download_volunteering_agreement'
    end
  end
  resources :observations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/observation.rb
class Observation < ApplicationRecord
  has_one :author, class_name: "User", foreign_key: "author_id"
  belongs_to :user
  validates :comment, length: { maximum: 300 }, presence: true
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_observation, only: [:show, :edit, :update, :destroy]

  # GET /observations
  # GET /observations.json
  def index
    @observations = Observation.all
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
  end

  # GET /observations/new
  def new
    @observation = Observation.new
  end

  # GET /observations/1/edit
  def edit
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(observation_params)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render :show, status: :created, location: @observation }
      else
        format.html { render :new }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /observations/1
  # PATCH/PUT /observations/1.json
  def update
    respond_to do |format|
      if @observation.update(observation_params)
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { render :show, status: :ok, location: @observation }
      else
        format.html { render :edit }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation.destroy
    respond_to do |format|
      format.html { redirect_to observations_url, notice: 'Observation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_observation
      @observation = Observation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def observation_params
      params.require(:observation).permit(:date, :comment, :positive, :user_id, :author_id)
    end
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/observations/_form.html.erb
<%= form_for(observation) do |f| %>
  <% if observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% observation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :positive %>
    <%= f.check_box :positive %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :author_id %>
    <%= f.number_field :author_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing Observation</h1>

<%= render 'form', observation: @observation %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Observations</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Comment</th>
      <th>Positive</th>
      <th>User</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @observations.each do |observation| %>
      <tr>
        <td><%= observation.date %></td>
        <td><%= observation.comment %></td>
        <td><%= observation.positive %></td>
        <td><%= observation.user_id %></td>
        <td><%= observation.author_id %></td>
        <td><%= link_to 'Show', observation %></td>
        <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
        <td><%= link_to 'Destroy', observation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Observation', new_observation_path %>

app/views/observations/new.html.erb
<h1>New Observation</h1>

<%= render 'form', observation: @observation %>

<%= link_to 'Back', observations_path %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @observation.date %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @observation.comment %>
</p>

<p>
  <strong>Positive:</strong>
  <%= @observation.positive %>
</p>

<p>
  <strong>User:</strong>
  <%= @observation.user_id %>
</p>

<p>
  <strong>Author:</strong>
  <%= @observation.author_id %>
</p>

<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>