config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :roles
  resources :jobs
  resources :users do
    member do
      get 'download_volunteering_agreement'
    end
  end
  resources :observations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  def self.identification_types
    %w(C.C. T.I.)
  end
  def self.careers_list
    ["Administración", "Contaduría Internacional", "Arquitectura", "Diseño", "Arte", "Historia del Arte", "Literatura", "Música", "Biología", "Física", "Geociencias", "Matemáticas", "Microbiología", "Química", "Antropología", "Ciencia Política", "Filosofía", "Historia", "Lenguas y Cultura", "Psicología", "Derecho", "Economía", "Licenciatura en Artes", "Licenciatura en Ciencias Naturales", "Licenciatura en Ciencias Sociales", "Licenciatura en Educación para la Primera Infancia", "Licenciatura en Humanidades", "Licenciatura en Matemáticas", "Ingeniería Ambiental", "Ingeniería Biomédica", "Ingeniería Civil", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Química", "Ingeniería de Sistemas y Computación", "Medicina", "Gobierno y Asuntos Públicos"]
  end
  has_many :observations
  mount_uploader :photo, PhotoUploader
  mount_uploader :volunteering_agreement, VolunteeringAgreementUploader
  serialize :careers, Array
  validates :name, length: { maximum: 140 }, presence: true
  validates :identification, numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :identification_type, inclusion: { in: identification_types }, presence: true
  validates :student_code, format: { with: /[0-9]{9}/ }, presence: true
  validates :email, length: { maximum: 140 }, presence: true
  validates :phone, format: { with: /[0-9]{9}/ }, presence: true
  validates :semester, numericality: { greater_than_or_equal_to: 1 }, presence: true
  validates :careers, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :download_volunteering_agreement]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_volunteering_agreement
    send_file "public/#{@user.volunteering_agreement.url}", disposition: 'attachment'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :identification, :identification_type, :student_code, :email, :phone, :photo, :semester, {:careers => []}, :volunteering_agreement)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, { class: "form-control", placeholder: "Nombre", required: true } %>
  </div>

  <div class="field">
    <%= f.label :identification %>
    <%= f.number_field :identification, { class: "form-control", placeholder: "Identificación", required: true } %>
  </div>

    <div class="field">
      <%= f.label :identification_type %>
      <%= f.select :identification_type, User.identification_types, {}, { class: "form-control" } %>
    </div>

  <div class="field">
    <%= f.label :student_code %>
    <%= f.number_field :student_code, { class: "form-control", placeholder: "Código de estudiante", required: true } %>
  </div>

    <div class="field">
      <%= f.label :email %>
      <div class="input-group">
        <%= f.text_field :email, { class: "form-control", placeholder: "Usuario Uniandes", required: true } %>
        <span class="input-group-addon">@uniandes.edu.co</span>
      </div>
    </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.number_field :phone, { class: "form-control", placeholder: "Teléfono celular", required: true } %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :semester %>
    <%= f.number_field :semester, { class: "form-control", placeholder: "Semestre", required: true } %>
  </div>

  <div class="field">
    <%= f.label :careers %>
    <%= f.select :careers, User.careers_list, { include_hidden: false }, { class: "form-control", multiple: true, required: true } %>
  </div>

  <div class="field">
    <%= f.label :volunteering_agreement %>
    <%= f.file_field :volunteering_agreement %>
  </div>

  <div class="actions">
    <%= f.submit 'Guardar', { class: "btn btn-default" } %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Identification</th>
      <th>Identification type</th>
      <th>Student code</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Photo</th>
      <th>Semester</th>
      <th>Careers</th>
      <th>Volunteering agreement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.identification %></td>
        <td><%= user.identification_type %></td>
        <td><%= user.student_code %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><img src="<%= user.photo %>"></td>
        <td><%= user.semester %></td>
        <td><%= user.careers %></td>
        <td><%= link_to 'Download', download_volunteering_agreement_user_path(user) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @user.identification %>
</p>

<p>
  <strong>Identification type:</strong>
  <%= @user.identification_type %>
</p>

<p>
  <strong>Student code:</strong>
  <%= @user.student_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @user.photo %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @user.semester %>
</p>

<p>
  <strong>Careers:</strong>
  <%= @user.careers %>
</p>

<p>
  <strong>Volunteering agreement:</strong>
  <%= @user.volunteering_agreement %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>